In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


In [6]:
p = torch.empty(2,3)

In [7]:
p

tensor([[1.2695e-11, 0.0000e+00, 2.1674e-11],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [8]:
type(p)

torch.Tensor

In [12]:
torch.zeros(3,7)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
torch.ones(4,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [16]:
torch.rand(15,5)

tensor([[0.5733, 0.4039, 0.4456, 0.7051, 0.2526],
        [0.2687, 0.2011, 0.0237, 0.8322, 0.9799],
        [0.3070, 0.8546, 0.1140, 0.9490, 0.0741],
        [0.4980, 0.2192, 0.5337, 0.3416, 0.2498],
        [0.4529, 0.5193, 0.6214, 0.7500, 0.3971],
        [0.1568, 0.9924, 0.5219, 0.0075, 0.3257],
        [0.0489, 0.0363, 0.8842, 0.4402, 0.6071],
        [0.0221, 0.0830, 0.9766, 0.3786, 0.3809],
        [0.9233, 0.4802, 0.1578, 0.7003, 0.2756],
        [0.2945, 0.1195, 0.3936, 0.7282, 0.7573],
        [0.7051, 0.8320, 0.2342, 0.7035, 0.8584],
        [0.8350, 0.2456, 0.6629, 0.2472, 0.8826],
        [0.3668, 0.4895, 0.4433, 0.2344, 0.4365],
        [0.1467, 0.2178, 0.9948, 0.2623, 0.4427],
        [0.0642, 0.2494, 0.4368, 0.5578, 0.6898]])

In [17]:
torch.manual_seed(60)
torch.rand(4,4)

tensor([[0.0236, 0.3107, 0.8581, 0.4991],
        [0.7348, 0.6979, 0.4319, 0.7147],
        [0.1445, 0.5976, 0.9530, 0.7818],
        [0.1302, 0.3420, 0.7089, 0.3218]])

In [19]:
torch.manual_seed(60)
torch.rand(6,6)

tensor([[0.0236, 0.3107, 0.8581, 0.4991, 0.7348, 0.6979],
        [0.4319, 0.7147, 0.1445, 0.5976, 0.9530, 0.7818],
        [0.1302, 0.3420, 0.7089, 0.3218, 0.6136, 0.0510],
        [0.5887, 0.9140, 0.2547, 0.9136, 0.8570, 0.3833],
        [0.3736, 0.5561, 0.0696, 0.2578, 0.6743, 0.0368],
        [0.0844, 0.8128, 0.3748, 0.3646, 0.4697, 0.0277]])

In [20]:
torch.tensor([[10,20,30],[40,50,60]])

tensor([[10, 20, 30],
        [40, 50, 60]])

In [21]:
# arange
print("using arange: ", torch.arange(0,11,3))

# using linspace
print("using linspace: ", torch.linspace(0,7,5))

# using eye
print("using eye: ", torch.eye(6))

# using full
print("using full: ", torch.full((3, 3), 8))

using arange:  tensor([0, 3, 6, 9])
using linspace:  tensor([0.0000, 1.7500, 3.5000, 5.2500, 7.0000])
using eye:  tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])
using full:  tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])


In [24]:
x = torch.tensor([[66,44,88],[88,44,66]])
x

tensor([[66, 44, 88],
        [88, 44, 66]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[          767789536,           769561920, 4575657222473777152],
        [7308604897285731189, 8319104481851616290, 3468370097086558057]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [29]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5339, 0.8345, 0.8320],
        [0.7801, 0.7333, 0.6404]])

In [30]:
x.dtype

torch.int64

In [31]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.tensor([55,33,66], dtype=torch.float64)

tensor([55., 33., 66.], dtype=torch.float64)

In [34]:
x.to(torch.float32)

tensor([[66., 44., 88.],
        [88., 44., 66.]])

In [35]:
x = torch.rand(2,2)
x

tensor([[0.5909, 0.8981],
        [0.8470, 0.9891]])

In [37]:
# addition
x + 2


tensor([[2.5909, 2.8981],
        [2.8470, 2.9891]])

In [38]:
# substraction
x - 2


tensor([[-1.4091, -1.1019],
        [-1.1530, -1.0109]])

In [39]:
# multiplication
x * 3


tensor([[1.7726, 2.6944],
        [2.5411, 2.9674]])

In [40]:
# division
x / 3


tensor([[0.1970, 0.2994],
        [0.2823, 0.3297]])

In [41]:
# int division
(x * 100)//3


tensor([[19., 29.],
        [28., 32.]])

In [42]:
# mod
((x * 100)//3)%2


tensor([[1., 1.],
        [0., 0.]])

In [43]:
# power
x**2

tensor([[0.3491, 0.8066],
        [0.7175, 0.9784]])

In [44]:
x = torch.rand(3,3)
y = torch.rand(3,3)

print(x)
print(y)

tensor([[0.8329, 0.4592, 0.0127],
        [0.7798, 0.9100, 0.2331],
        [0.0809, 0.8017, 0.6028]])
tensor([[0.2515, 0.2095, 0.3356],
        [0.4103, 0.0480, 0.9314],
        [0.5751, 0.2885, 0.0324]])


In [45]:
#add
x + y

tensor([[1.0844, 0.6687, 0.3483],
        [1.1901, 0.9581, 1.1645],
        [0.6560, 1.0902, 0.6352]])

In [46]:
#subtract
x - y

tensor([[ 0.5813,  0.2497, -0.3229],
        [ 0.3695,  0.8620, -0.6983],
        [-0.4942,  0.5132,  0.5704]])

In [47]:
#multiplication
x * y

tensor([[0.2095, 0.0962, 0.0043],
        [0.3200, 0.0437, 0.2171],
        [0.0465, 0.2313, 0.0195]])

In [48]:
#division
x/y

tensor([[ 3.3114,  2.1921,  0.0378],
        [ 1.9004, 18.9422,  0.2503],
        [ 0.1407,  2.7787, 18.6057]])

In [49]:
#power
x ** y

tensor([[0.9550, 0.8496, 0.2308],
        [0.9030, 0.9955, 0.2576],
        [0.2355, 0.9382, 0.9837]])

In [50]:
#mod
x % y

tensor([[0.0783, 0.0402, 0.0127],
        [0.3695, 0.0453, 0.2331],
        [0.0809, 0.2247, 0.0196]])

In [59]:
a = torch.tensor([10, -20, 30, -40])

In [60]:
# abs
torch.abs(a)

tensor([10, 20, 30, 40])

In [61]:
# negative
torch.neg(a)

tensor([-10,  20, -30,  40])

In [62]:
b = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [63]:
# round
torch.round(b)

tensor([2., 2., 4., 4.])

In [64]:
# ceil
torch.ceil(b)

tensor([2., 3., 4., 5.])

In [65]:
# floor
torch.floor(b)

tensor([1., 2., 3., 4.])

In [66]:
# clamp
torch.clamp(b, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [67]:
c = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
c

tensor([[7., 8., 0.],
        [2., 1., 0.]])

In [68]:
torch.sum(c, dim=0)

tensor([9., 9., 0.])

In [70]:
# sum
torch.sum(c)

tensor(18.)

In [72]:
# sum along columns
torch.sum(c, dim=0)

tensor([9., 9., 0.])

In [73]:
# sum along rows
torch.sum(c, dim=1)

tensor([15.,  3.])

In [74]:
# mean
torch.mean(c)

tensor(3.)

In [75]:
# mean along col
torch.mean(c, dim=0)

tensor([4.5000, 4.5000, 0.0000])

In [76]:
# median
torch.median(c)

tensor(1.)

In [77]:
# max and min
torch.max(c)
torch.min(c)

tensor(0.)

In [78]:
# product
torch.prod(c)

tensor(0.)

In [79]:
# standard deviation
torch.std(c)

tensor(3.5777)

In [80]:
# variance
torch.var(c)

tensor(12.8000)

In [81]:
# argmax
torch.argmax(c)

tensor(1)

In [82]:
# argmin
torch.argmin(c)

tensor(2)

In [83]:
d= torch.randint(size=(2,3), low=0, high=10)
e= torch.randint(size=(3,2), low=0, high=10)

print(d)
print(e)

tensor([[0, 2, 9],
        [3, 8, 0]])
tensor([[5, 2],
        [4, 9],
        [1, 7]])


In [84]:
# matrix multiplcation
torch.matmul(d,e)

tensor([[17, 81],
        [47, 78]])

In [85]:
vector1 = torch.tensor([9,8])
vector2 = torch.tensor([7,6])

# dot product
torch.dot(vector1, vector2)

tensor(111)

In [88]:
# transpose
torch.transpose(d, 0, 1)

tensor([[0, 3],
        [2, 8],
        [9, 0]])

In [90]:
f = torch.randint(size=(4,4), low=0, high=20, dtype=torch.float32)
f

tensor([[ 7.,  0., 14.,  8.],
        [19.,  5., 11., 11.],
        [ 0.,  2., 15.,  7.],
        [ 3., 10.,  9.,  6.]])

In [91]:
# determinant
torch.det(f)

tensor(-842.9989)

In [92]:
# inverse
torch.inverse(f)

tensor([[ 0.8055, -0.2894, -0.7117,  0.2871],
        [ 0.2954, -0.1459, -0.3096,  0.2349],
        [ 1.2610, -0.5386, -0.9964,  0.4686],
        [-2.7865,  1.1957,  2.3666, -1.0712]])

In [93]:
g= torch.randint(size=(3,4), low=5, high=20)
h= torch.randint(size=(3,4), low=5, high=20)

print(g)
print(h)

tensor([[12, 18, 18,  7],
        [ 9, 11, 16, 13],
        [15,  5, 10,  9]])
tensor([[19, 18,  7, 14],
        [14,  8, 18, 17],
        [16, 11,  6,  6]])


In [94]:
# greater than
g > h



tensor([[False, False,  True, False],
        [False,  True, False, False],
        [False, False,  True,  True]])

In [95]:
# less than
g < h



tensor([[ True, False, False,  True],
        [ True, False,  True,  True],
        [ True,  True, False, False]])

In [96]:
# equal to
g == h



tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [97]:
# not equal to
g != h



tensor([[ True, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [98]:
# greater than equal to
g >= h



tensor([[False,  True,  True, False],
        [False,  True, False, False],
        [False, False,  True,  True]])

In [99]:
# less than equal to
g <= h

tensor([[ True,  True, False,  True],
        [ True, False,  True,  True],
        [ True,  True, False, False]])

In [100]:
i = torch.randint(size=(2,3), low=0, high=15, dtype=torch.float32)
i

tensor([[13., 11., 10.],
        [13.,  4., 14.]])

In [101]:
#log
torch.log(i)

tensor([[2.5649, 2.3979, 2.3026],
        [2.5649, 1.3863, 2.6391]])

In [102]:
# exp
torch.exp(i)

tensor([[4.4241e+05, 5.9874e+04, 2.2026e+04],
        [4.4241e+05, 5.4598e+01, 1.2026e+06]])

In [103]:
# sqrt
torch.sqrt(i)

tensor([[3.6056, 3.3166, 3.1623],
        [3.6056, 2.0000, 3.7417]])

In [104]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(i)

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 0.9820, 1.0000]])

In [105]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(i, dim=0)

tensor([[5.0000e-01, 9.9909e-01, 1.7986e-02],
        [5.0000e-01, 9.1105e-04, 9.8201e-01]])

In [109]:
# relu
torch.relu(x)

tensor([[0.8329, 0.4592, 0.0127],
        [0.7798, 0.9100, 0.2331],
        [0.0809, 0.8017, 0.6028]])

In [110]:
j= torch.rand(2,3)
k= torch.rand(2,3)

print(j)
print(k)

tensor([[0.3509, 0.4002, 0.1545],
        [0.7791, 0.3317, 0.1046]])
tensor([[0.8373, 0.0168, 0.4796],
        [0.0654, 0.7786, 0.8749]])


In [112]:
j.add_(k)

tensor([[1.1881, 0.4170, 0.6340],
        [0.8445, 1.1103, 0.9795]])

In [113]:
j

tensor([[1.1881, 0.4170, 0.6340],
        [0.8445, 1.1103, 0.9795]])

In [114]:
k

tensor([[0.8373, 0.0168, 0.4796],
        [0.0654, 0.7786, 0.8749]])

In [115]:
torch.relu(j)

tensor([[1.1881, 0.4170, 0.6340],
        [0.8445, 1.1103, 0.9795]])

In [117]:
j.relu_()

tensor([[1.1881, 0.4170, 0.6340],
        [0.8445, 1.1103, 0.9795]])

In [118]:
j

tensor([[1.1881, 0.4170, 0.6340],
        [0.8445, 1.1103, 0.9795]])

In [119]:
k = torch.rand(3,3)
k

tensor([[0.9000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [120]:
l=k

In [121]:
l

tensor([[0.9000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [122]:
k[0][0]=0

In [123]:
k

tensor([[0.0000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [124]:
l

tensor([[0.0000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [125]:
id(k)

135320979096032

In [126]:
id(l)

135320979096032

In [127]:
l=k.clone()

In [128]:
k

tensor([[0.0000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [129]:
l

tensor([[0.0000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [130]:
k[0][0] = 10

In [131]:
k

tensor([[10.0000,  0.2667,  0.5977],
        [ 0.9637,  0.2070,  0.0424],
        [ 0.9681,  0.0367,  0.5415]])

In [132]:
l

tensor([[0.0000, 0.2667, 0.5977],
        [0.9637, 0.2070, 0.0424],
        [0.9681, 0.0367, 0.5415]])

In [133]:
id(k)

135320979096032

In [134]:
id(l)

135320979055760

In [135]:
k= torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
k

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [136]:
k.shape

torch.Size([3, 3])

In [137]:
l = torch.empty_like(k)
l

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067248292745456950, 3760851176849551666, 6499029846229792558],
        [7309453675965983778, 8315168162784306286, 8367752027310484831]])