In [1]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
tf.__version__

'2.20.0'

In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [5]:
x= tf.constant(10)
x


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
y= tf.constant(10.5)
y


<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [7]:
z=tf.constant("India")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [8]:
s=tf.constant([10,20,30,40,50,60])
s

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([10, 20, 30, 40, 50, 60], dtype=int32)>

In [9]:
import numpy as np

a = np.array([[10,20,30], [40,50,60]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

In [10]:
t_2d=tf.constant([[11,66],[33,88]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 66],
       [33, 88]], dtype=int32)>

In [11]:
t_1d=tf.constant([21,22,23,24])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([21, 22, 23, 24], dtype=int32)>

In [12]:
t_2d_1=tf.constant([15,82,53,55],shape=(2,2),dtype="int32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 82],
       [53, 55]], dtype=int32)>

In [13]:
t_3d_1=tf.constant([[[1,2],[10,20],[100,200]]],dtype="float32")
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[  1.,   2.],
        [ 10.,  20.],
        [100., 200.]]], dtype=float32)>

In [14]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [15]:
t_3d_1.shape

TensorShape([1, 3, 2])

In [16]:
import tensorflow as tf

In [17]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [18]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [19]:
x.name


'Variable:0'

In [20]:
x.shape

TensorShape([4])

In [21]:
x.dtype

tf.int32

In [23]:
y=tf.Variable([1.01,2,3.5,4])

In [24]:
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.01, 2.  , 3.5 , 4.  ], dtype=float32)>

In [25]:
z=tf.Variable(True,False)

In [26]:
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [27]:
t_con=tf.constant([1,2,3,4])

In [28]:
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [29]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [30]:
# Create Tensorflow variable with different Shape

In [32]:
t_2d=tf.Variable([[10,20],[30,40]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [33]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [34]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [35]:
# Get index of highest value

In [36]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [37]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [38]:
# Viewed/Convert as a Tensor

In [39]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [40]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [41]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [42]:
# Change/Assign New Value to Tensor

In [43]:
x=tf.Variable([44,55,66,77])
x


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([44, 55, 66, 77], dtype=int32)>

In [45]:
x.assign([55,44,33,22])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([55, 44, 33, 22], dtype=int32)>

In [46]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([55, 44, 33, 22], dtype=int32)>

In [47]:
x.assign([10,20,100,200])


<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 10,  20, 100, 200], dtype=int32)>

In [48]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 10,  20, 100, 200], dtype=int32)>

In [49]:
# Assign  addition variable with another Memory

In [50]:
x.assign_add([10,50,100,150])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 20,  70, 200, 350], dtype=int32)>

In [51]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 20,  70, 200, 350], dtype=int32)>

In [52]:
#Tensorflow math modules

In [53]:
import tensorflow as tf
import numpy as np

In [54]:
a=2
b=2

In [55]:
a+b

4

In [56]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [59]:
#Addition of Two List

l1=[1,2,3,4]
l2=[1,2,3,4]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [60]:
# Addition of Two tuple
t1=(2,3,4,5)
t2=(10,10,10,10)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 13, 14, 15], dtype=int32)>

In [61]:
l1=[11,22,33,44]
a=100
tf.add(l1,a)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([111, 122, 133, 144], dtype=int32)>

In [62]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [63]:
x = tf.constant([-6.20, 3.44])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([6.2 , 3.44], dtype=float32)>

In [64]:
x = tf.constant([[-2.50 + 8.75j], [-1.50 + 5.05j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[9.10013736],
       [5.26806416]])>

In [65]:
x = [11,21,31,41,51]
y = 1
tf.subtract(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50], dtype=int32)>

In [66]:
x = [11,21,31,41,51]
y = 1
tf.subtract(y, x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-10, -20, -30, -40, -50], dtype=int32)>

In [67]:
import tensorflow as tf
x = tf.constant(([10,20,30,40]))
tf.math.multiply(x, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 100,  400,  900, 1600], dtype=int32)>

In [68]:
tf.multiply(x, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 100,  400,  900, 1600], dtype=int32)>

In [69]:
tf.math.multiply(100,6)


<tf.Tensor: shape=(), dtype=int32, numpy=600>

In [71]:
x = tf.ones([1, 2]);
y = tf.ones([2, 1]);
x * y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [72]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [73]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [74]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-5., -2., 0., 3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [75]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [76]:
x = tf.constant([0, 0.5, 1, 5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [77]:
x = tf.constant([100,200,300])
y = tf.constant([10,10,10])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([10., 20., 30.])>

In [78]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [79]:
x = tf.constant([[4.0], [16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [80]:
y = tf.constant([[-4.0], [16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [81]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [82]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [83]:
ones_2d= tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [84]:
ones_3d=tf.ones((2,2,4),tf.float32)

In [85]:
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [86]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [87]:
zeros_2d=tf.zeros((2,2),dtype=tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [89]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [90]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [92]:
#Placeholder-Migrate tensorflow 1 code to tensorflow 2
#Place holder is a variable that we will assign data to at a later date.

In [93]:
import tensorflow as tf

In [101]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


In [102]:
input_var = tf.Variable(tf.zeros((400, 400), dtype=tf.float32))

print("Created Variable with shape:", input_var.shape)

Created Variable with shape: (400, 400)


In [103]:
tf.compat.v1.disable_eager_execution()

In [104]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [105]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_3:0' shape=(400, 400) dtype=float32>

In [106]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [107]:
import numpy as np

In [113]:
ones_array=np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [114]:
with tf.compat.v1.Session() as sess:
   d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [115]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

In [116]:
#Sparse Tensors
#It enables efficient storage & processing of tensors that contains lot of zero values

In [117]:
tf.SparseTensor()


TypeError: SparseTensor.__init__() missing 3 required positional arguments: 'indices', 'values', and 'dense_shape'

In [118]:
tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [119]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))

In [120]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))


In [121]:
import tensorflow as tf

x = tf.compat.v1.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
y = tf.compat.v1.get_variable("y", dtype=tf.int32,  initializer=tf.constant([6]))


In [122]:
c = tf.constant([5], name ="constant")
square = tf.constant([2], name ="square")
f = tf.multiply(x, y) + tf.pow(x, square) + y + c
f


<tf.Tensor 'add_3:0' shape=(1,) dtype=int32>